name: web_proyect
services:
- name: server
  github:
    repo: Hectorc70/web_lorena
    branch: master
    deploy_on_push: true
  run_command: gunicorn --worker-tmp-dir /dev/shm web_proyect.wsgi
  envs:
  - key: DISABLE_COLLECTSTATIC
    value: "1"
    scope: BUILD_TIME
  - key: DATABASE_URL
    value: "${db.DATABASE_URL}"
    scope: RUN_TIME
  - key: DJANGO_ALLOWED_HOSTS
    value: "${APP_DOMAIN}"
    scope: RUN_TIME
jobs:
- name: migrate
  kind: PRE_DEPLOY
  github:
    repo: Hectorc70/web_lorena
    branch: master
    deploy_on_push: false
  run_command: python manage.py migrate
  envs:
  - key: DISABLE_COLLECTSTATIC
    value: "1"
    scope: BUILD_TIME
  - key: DATABASE_URL
    value: "${db.DATABASE_URL}"
    scope: RUN_TIME
static_sites:
- name: static
  github:
    repo: Hectorc70/web_lorena
    branch: master
    deploy_on_push: true
  # This happens as part of the Python/DJango buildpack:
  # build_command: python manage.py collectstatic --noinput
  output_dir: staticfiles
  routes:
  - path: /static
databases:
