# Generated by Django 3.0.2 on 2021-08-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lifeinsurance',
            options={'verbose_name': 'Seguro de Vida', 'verbose_name_plural': 'Seguros de Vida'},
        ),
        migrations.AlterModelTable(
            name='lifeinsurance',
            table='Life_Insurance',
        ),
    ]
