# Generated by Django 3.0.2 on 2021-08-31 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210830_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurancecar',
            old_name='num_cel',
            new_name='num_phone',
        ),
    ]
