# Generated by Django 3.0.2 on 2021-08-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210830_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancehouse',
            name='municipality',
        ),
        migrations.AddField(
            model_name='insurancehouse',
            name='city',
            field=models.CharField(db_column='City', default=1, max_length=48, verbose_name='Ciudad'),
            preserve_default=False,
        ),
    ]
